class DatabaseProviderHelper {

  /////////////////// EVENT TABLE   ///////////////////////

  static const String TABLE_EVENTS = "EVENTS"; // main table name
  static const String EVENT_ID = "EVENT_ID"; // main table name
  static const String EVENT_NAME = "EVENT_NAME"; // strings
  static const String EVENT_DISCRIPTION = "EVENT_DISCRIPTION"; // strings
  static const String EVENT_COLOR_NUMBER = "EVENT_COLOR_NUMBER";//int
  static const String ITS_MONTH_IT = "ITS_MONTH_INTERVAL"; // boolean
  static const String MONTH_IT_QUANTITY_OF_REPEATS = "MONTH_IT_QUANTITY_OF_REPEATS"; // int
  static const String MONTH_IT_DAY_OF_MONTH = "MONTH_IT_DAY_OF_MONTH"; // int
  static const String ITS_CUSTOM_TI = "ITS_CUSTOM_TI"; // boolean
  static const String CUSTOM_TIME_IT_TYPE = "CUSTOM_TIME_IT_TYPE"; // type (0 - none, 1 - day,2 - week,3 - month)
  static const String CUSTOM_TIME_IT_REPEATS_ALL_TIME = "CUSTOM_TIME_IT_REPEATS_ALL_TIME";// boolean
  static const String CUSTOM_TIME_IT_QUANTITY_OF_REPEATS = "CUSTOM_TIME_IT_QUANTITY_OF_REPEATS"; // int
  static const String CUSTOM_TIME_IT_TIME_INTERVAL = "CUSTOM_TIME_IT_TIME_INTERVAL"; // int
  static const String ITS_ONE_TIME_TYPE = "ITS_ONE_TIME_TYPE"; // boolean
  static const String ONE_TIME_TYPE_DATE = "ONE_TIME_TYPE_DATE"; // date
  static const String START_DATE_MILLIS = "START_DATE_MILLIS"; // date
  static const String START_DATE_STRING = "START_DATE_STRING"; // date
  static const String ITS_EVENT_DEFAULT_TIME = "ITS_EVENT_DEFAULT_TIME";
  static const String EVENT_TIME_MILLIS = "EVENT_TIME_MILLIS";
  static const String EVENT_TIME_STRING = "EVENT_TIME_STRING";

  static const List<String> EVENT_TABLE_COLUMN = [EVENT_NAME,
    EVENT_DISCRIPTION,
    EVENT_COLOR_NUMBER,
    ITS_MONTH_IT,
    MONTH_IT_QUANTITY_OF_REPEATS,
    MONTH_IT_DAY_OF_MONTH,
    ITS_CUSTOM_TI,
    CUSTOM_TIME_IT_TYPE,
    CUSTOM_TIME_IT_REPEATS_ALL_TIME,
    CUSTOM_TIME_IT_QUANTITY_OF_REPEATS,
    CUSTOM_TIME_IT_TIME_INTERVAL,
    ITS_ONE_TIME_TYPE,
    ONE_TIME_TYPE_DATE,
    START_DATE_MILLIS,
    START_DATE_STRING,
    ITS_EVENT_DEFAULT_TIME,
    EVENT_TIME_MILLIS,
    EVENT_TIME_STRING];

  static const String CREATE_EVENT_TABLE_STRING = ''' CREATE TABLE $TABLE_EVENTS ( 
    $EVENT_ID INTEGER PRIMARY KEY,
    $EVENT_NAME TEXT NOT NULL,
    $EVENT_DISCRIPTION TEXT,
    $EVENT_COLOR_NUMBER INTEGER DEFAULT 0,
    $ITS_MONTH_IT INTEGER DEFAULT 0,
    $MONTH_IT_QUANTITY_OF_REPEATS INTEGER DEFAULT 0,
    $MONTH_IT_DAY_OF_MONTH INTEGER DEFAULT 0,
    $ITS_CUSTOM_TI INTEGER DEFAULT 0,
    $CUSTOM_TIME_IT_TYPE INTEGER DEFAULT 0,
    $CUSTOM_TIME_IT_REPEATS_ALL_TIME INTEGER DEFAULT 0,
    $CUSTOM_TIME_IT_QUANTITY_OF_REPEATS INTEGER DEFAULT 0,
    $CUSTOM_TIME_IT_TIME_INTERVAL INTEGER DEFAULT 0,
    $ITS_ONE_TIME_TYPE INTEGER DEFAULT 0,
    $ONE_TIME_TYPE_DATE REAL DEFAULT 0,
    $START_DATE_MILLIS REAL DEFAULT 0,
    $START_DATE_STRING TEXT,
    $ITS_EVENT_DEFAULT_TIME INTEGER DEFAULT 0,
    $EVENT_TIME_MILLIS REAL DEFAULT 0,
    $EVENT_TIME_STRING TEXT); ''';

  ////////////////////////////////////////////////////////////

  /////////////////// EVENT DETAIL TABLE   ///////////////////
  static const String TEMPLATE_TABLE_ID = "id";
  static const String TEMPLATE_TABLE_DAY_MILLIS = "DAY_MILLIS";
  static const String TEMPLATE_TABLE_DAY_STRING = "DAY_STRING";
  static const String TEMPLATE_TABLE_NOTIFICATION_CREATED = "NOTIFICATION_CREATED";
  static const String TEMPLATE_TABLE_NOTIFICATION_DISPLAYED = "NOTIFICATION_DISPLAYED";
  static const String TEMPLATE_TABLE_EVENT_DONE = "EVENT_DONE";

  ///////////////////////////////////////////////////////////

  /////////////// NOTIFICATION TABLE ////////////////////////
  static const String TABLE_NOTIFICATIONS = "NOTIFICATIONS";
  static const String NOTIFICATION_ID = "NOTIFICATION_ID";
  static const String NOTIFICATION_EVENT_NAME = "NOTIFICATION_EVENT_NAME";
  static const String NOTIFICATION_ALARM_ID = "NOTIFICATION_ALARM_ID";
  static const String NOTIFICATION_DATE_MILLIS = "NOTIFICATION_DATE_MILLIS";
  static const String NOTIFICATION_DATE_STRING = "NOTIFICATION_DATE_STRING";
  static const String NOTIFICATION_TIME_STRING = "NOTIFICATION_TIME_STRING";
  static const String NOTIFICATION_TIME_DOUBLE = "NOTIFICATION_TIME_DOUBLE";
  static const String NOTIFICATION_COMPLETED = "NOTIFICATION_COMPLETED";

  static const String CREATE_NOTIFICATION_TABLE_STRING = ''' CREATE TABLE $TABLE_NOTIFICATIONS ( 
    $NOTIFICATION_ID INTEGER PRIMARY KEY,
    $NOTIFICATION_EVENT_NAME TEXT,
    $NOTIFICATION_ALARM_ID INTEGER,
    $NOTIFICATION_DATE_MILLIS INTEGER,
    $NOTIFICATION_DATE_STRING TEXT,
    $NOTIFICATION_TIME_STRING TEXT,
    $NOTIFICATION_TIME_DOUBLE REAL,
    $NOTIFICATION_COMPLETED INTEGER DEFAULT 0); ''';

  static const List<String> NOTIFICATION_TABLE_COLUMN = [NOTIFICATION_EVENT_NAME,
    NOTIFICATION_ALARM_ID,
    NOTIFICATION_DATE_MILLIS,
    NOTIFICATION_DATE_STRING,
    NOTIFICATION_TIME_STRING,
    NOTIFICATION_TIME_DOUBLE,
    NOTIFICATION_COMPLETED];

  ///////////////////////////////////////////////////////////

}